require:
  - rubocop-rails
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "tmp/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - "test/**/*"
    - "*.gemspec"

Layout/LineLength:
  Max: 120
